export const projectConstants = {
    "ROOTUIPATH": "https://scale.jaldee.com",
    "TEMPLATE": "https://d38qirwztuxwob.cloudfront.net/template",
    "HOME": "https://d38qirwztuxwob.cloudfront.net/home",
    "template1": "https://d38qirwztuxwob.cloudfront.net/template1",
    "template2": "https://d38qirwztuxwob.cloudfront.net/template2",
    "template3": "https://d38qirwztuxwob.cloudfront.net/template3",
    "template4": "https://d38qirwztuxwob.cloudfront.net/template4", 
    "template5": "https://d38qirwztuxwob.cloudfront.net/template5", 
    "template6": "https://d38qirwztuxwob.cloudfront.net/template6", 
    "template7": "https://d38qirwztuxwob.cloudfront.net/template7", 
    "template8": "https://d38qirwztuxwob.cloudfront.net/template8", 
    "template9": "https://d38qirwztuxwob.cloudfront.net/template9", 
    "template10": "https://d38qirwztuxwob.cloudfront.net/template10", 
    "template11": "https://d38qirwztuxwob.cloudfront.net/template11", 
    "template12": "https://d38qirwztuxwob.cloudfront.net/template12", 
    "APIENDPOINT": "https://scale.jaldee.com/v1/rest/",
    "S3ENDPOINT": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/",
    "SAPATH": "https://sascale.jaldee.com/superadmin/rest/mgmt/",
    "I8NPATH": "https://d2199iy1o5ikw9.cloudfront.net/",
    "CDNURL": "https://d2199iy1o5ikw9.cloudfront.net/",
    "INTL_TEL_INPUT_PATH": "global/intl-tel-input-v1/",
    "GOOGLEAPIKEY": "AIzaSyDYIC4RIJNisNqXWDhe8y07EPSy9rHJ3-o",
    "UNIQUEID": null
}
