import { Component, ElementRef, Input, ViewChild } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ChotaBossStateService, Product } from './chotaboss-state.service';
import { chotaBossAssetUrl } from './chotaboss-assets';

@Component({ selector: 'cb-quantity', template: `
  <div class="quantity" *ngIf="state.quantity(product.id); else add"><button aria-label="Remove one" (click)="state.changeQuantity(product,-1)">−</button><b>{{state.quantity(product.id)}}</b><button aria-label="Add one" (click)="state.changeQuantity(product,1)">+</button></div>
  <ng-template #add><button class="add-button" type="button" [attr.aria-label]="'Add '+product.name" (click)="state.changeQuantity(product,1)">+</button></ng-template>` })
export class QuantityComponent { @Input({ required: true }) product!: Product; constructor(public readonly state: ChotaBossStateService) {} }

@Component({ selector: 'cb-shop-page', template: `
  <main class="app-page with-nav shop-page"><section class="shop-top"><cb-header [logo]="true" [orange]="true"><a class="delivery" routerLink="../locations">⌖ <small>Deliver at</small><b>Home⌄</b></a><a class="icon-button light" routerLink="../store/pedigree" aria-label="Cart">♙</a><a class="icon-button light" routerLink="../support" aria-label="Profile">●</a></cb-header><a class="search-box" routerLink="../search">◔ &nbsp; Search for “Skin Medicine”</a></section>
    <section class="store-categories"><h1>Pet Store</h1><p>🐾 Fast Delivery from Your Nearby Pet Store</p><div class="shop-category-row"><a *ngFor="let cat of categories" routerLink="../search"><img [src]="cat.image" [alt]="cat.name"><b>{{cat.name}}</b></a></div><a class="see-all" routerLink="../search">See all »</a></section>
    <section class="page-pad"><div class="section-heading"><h2>Brands</h2><a routerLink="../search">See all »</a></div><div class="brand-row"><button *ngFor="let brand of brands" (click)="openStore()"><img [src]="brand.image" [alt]="brand.name"><span>{{brand.name}}</span></button></div></section>
    <section class="shops-section page-pad"><div class="section-heading"><h2>Shops</h2><a routerLink="../search">See all »</a></div><div class="shop-row"><article *ngFor="let shop of ['Pedigree Official Store','Pet Pharmacy']"><div class="shop-logo">🐾</div><h3>{{shop}}</h3><p>⌖ Thrissur</p><button (click)="openStore()">View Store</button></article></div><img class="promo-image" [src]="assetUrl('christmas-offer.jpg')" alt="Christmas offer: 25 percent off"></section><cb-bottom-nav></cb-bottom-nav>
  </main>` })
export class ShopPageComponent {
  readonly assetUrl = chotaBossAssetUrl;
  readonly categories=[{name:'Pharmacy',image:chotaBossAssetUrl('shop-pharmacy.jpg')},{name:'Accessories',image:chotaBossAssetUrl('shop-accessories.jpg')},{name:'Foods',image:chotaBossAssetUrl('shop-foods.jpg')}];
  readonly brands=[{name:'Pedigree',image:chotaBossAssetUrl('brand-pedigree.png')},{name:'Royal Canin',image:chotaBossAssetUrl('brand-royal-canin.png')},{name:'Farmina',image:chotaBossAssetUrl('brand-farmina.png')},{name:'Drools',image:chotaBossAssetUrl('brand-drools.png')}];
  constructor(private readonly router: Router, private readonly route: ActivatedRoute) {} openStore(): void { void this.router.navigate(['../store/pedigree'], { relativeTo: this.route }); }
}

@Component({ selector: 'cb-search-page', template: `
  <main class="app-page"><cb-header title="Search for items & Store" [back]="true"></cb-header><section class="page-pad"><label class="search-input">⌕<input [(ngModel)]="query" placeholder="Search items and stores" aria-label="Search items and stores"><button type="button" aria-label="Clear search" (click)="query=''">×</button></label></section>
    <ng-container *ngIf="filteredProducts.length || filteredStores.length; else noResults"><section class="suggestions"><h2>Item Suggestions</h2><button *ngFor="let product of filteredProducts" (click)="openStore()"><img [src]="product.image" [alt]="product.name"><span><b>{{product.name}}</b><small>{{product.category}} · {{product.variant}}</small></span><i>›</i></button></section><section class="suggestions stores"><h2>Store Suggestions</h2><button *ngFor="let store of filteredStores" (click)="openStore()"><span class="result-logo">{{store.icon}}</span><span><b>{{store.name}} <em *ngIf="store.verified">●</em></b><small>{{store.meta}}</small></span><i>›</i></button></section></ng-container>
    <ng-template #noResults><section class="empty-state"><div class="empty-icon">⌕</div><h2>No results found</h2><p>Try another item, brand, or store.</p><button class="primary" (click)="query=''">Clear search</button></section></ng-template>
  </main>` })
export class SearchPageComponent {
  query='Pedigre'; readonly stores=[{name:'Pedigree Official Store',icon:'Pedigree',meta:'1.2 km · Online & Physical Store',verified:true},{name:'Pet Pharmacy',icon:'✚',meta:'0.8 km · Jl. Sudirman No. 45',verified:false},{name:'Animal House Store',icon:'AH',meta:'2.4 km · Jl. Gatot Subroto No. 12',verified:false}];
  constructor(public readonly state: ChotaBossStateService,private readonly router:Router,private readonly route:ActivatedRoute){}
  get filteredProducts(): Product[]{const q=this.query.toLowerCase(); if(!q)return this.state.products; return this.state.products.filter((item)=>item.name.toLowerCase().includes(q)||'pedigree'.includes(q));}
  get filteredStores(){const q=this.query.toLowerCase(); if(!q)return this.stores; return this.stores.filter((item)=>item.name.toLowerCase().includes(q)||'pedigree'.includes(q));}
  openStore():void{void this.router.navigate(['../store/pedigree'], { relativeTo: this.route });}
}

@Component({ selector: 'cb-store-page', template: `
  <main class="app-page store-page" [class.has-cart]="state.itemCount"><cb-header title="Pedigree Official Store" [back]="true"><button class="icon-button" aria-label="Share store" (click)="share()">⇧</button></cb-header><img class="store-hero" [src]="assetUrl('store-hero.jpg')" alt="Pedigree Official Store interior"><section class="store-info page-pad"><div class="store-logo">Pedigree</div><h1>Pedigree Official Store <span>✪</span></h1><p><b>☆ 4.8</b> (2.3k reviews) &nbsp;&nbsp; ⌖ 1.2 km away</p><div><span>Online & Physical Store</span><strong>Open Now</strong></div><p>♧ &nbsp; Jl. Sudirman No. 45, Westfort, Thrissur, Kerala</p><label class="search-input disabled">⌕<input placeholder="Search Item" aria-label="Search store items"></label><div class="category-chips"><button *ngFor="let category of ['All','Dry Food','Wet Food','Treats']" [class.active]="category==='All'">{{category}}</button></div><div class="section-heading"><h2>Top Products</h2><button>View All</button></div><div class="product-grid"><article *ngFor="let product of catalogue"><div class="product-image"><span *ngIf="product.discount">{{product.discount}}% OFF</span><img [src]="product.image" [alt]="product.name"></div><h3>{{product.name}}</h3><div class="product-price"><p><b>₹{{product.price}}</b><del *ngIf="product.originalPrice">₹{{product.originalPrice}}</del></p><div class="quantity" *ngIf="state.quantity(product.id); else add"><button (click)="state.changeQuantity(product,-1)">−</button><b>{{state.quantity(product.id)}}</b><button (click)="state.changeQuantity(product,1)">+</button></div><ng-template #add><button class="add-button" (click)="state.changeQuantity(product,1)" [attr.aria-label]="'Add '+product.name">+</button></ng-template></div></article></div></section>
    <div *ngIf="state.itemCount" class="cart-summary"><span>🛒</span><div><small>{{state.itemCount}} item{{state.itemCount===1?'':'s'}} in cart</small><b>₹{{state.subtotal}}</b></div><a routerLink="../checkout">Checkout</a></div>
  </main>` })
export class StorePageComponent {
  readonly assetUrl = chotaBossAssetUrl;
  get catalogue():Product[]{return [...this.state.products,...this.state.products];}
  constructor(public readonly state:ChotaBossStateService){}
  async share():Promise<void>{if(navigator.share)await navigator.share({title:'Pedigree Official Store'});}
}

@Component({ selector: 'cb-checkout-page', template: `
  <main class="app-page checkout-page action-page"><cb-header title="Pedigree Official Store" [back]="true"></cb-header><div class="delivery-bar">⌂ &nbsp; <b>34 min to Home</b><span>| CB904 Salarpuri Gr...</span><i>⌄</i></div><section class="checkout-content page-pad"><article class="cart-card"><div *ngFor="let line of state.cart" class="checkout-line"><img [src]="line.product.image" [alt]="line.product.name"><div><b>{{line.product.name}}</b><small>{{line.product.category}} · {{line.product.variant}}</small></div><div class="quantity"><button (click)="state.changeQuantity(line.product,-1)">−</button><b>{{line.quantity}}</b><button (click)="state.changeQuantity(line.product,1)">+</button></div><p><del *ngIf="line.product.originalPrice">₹{{line.product.originalPrice}}</del><b>₹{{line.product.price*line.quantity}}</b></p></div><a routerLink="../store/pedigree">⊕ &nbsp; Add more items <span>＋</span></a><button type="button" (click)="editNote()">♢ &nbsp; {{state.note || 'Add Any Note'}} <span>✎</span></button><div *ngIf="editingNote" class="note-editor"><label for="order-note">Order note</label><textarea #note id="order-note" [value]="state.note" maxlength="120"></textarea><button (click)="saveNote(note.value)">Save note</button></div></article><h2>Offers & Benefits</h2><button class="coupon-card" (click)="state.toggleCoupon()">🎟 &nbsp; <span><b>{{state.couponApplied?'Coupon Applied':'Apply Coupon'}}</b><small>{{state.couponApplied?'CHOTABOSS saves ₹25':'Save another ₹25 with CHOTABOSS'}}</small></span><i>{{state.couponApplied?'✓':'›'}}</i></button><article class="totals"><p><span>Subtotal</span><b>₹{{state.subtotal}}.00</b></p><p><span>Delivery Fee</span><b>₹{{state.deliveryFee}}.00</b></p><p class="discount"><span>Discount (15% OFF)</span><b>−₹{{state.discount}}.00</b></p><hr><p class="grand"><span>Total</span><b>₹{{state.total}}.00</b></p></article></section>
    <section class="payment-panel"><div><span class="gpay">G</span><p><small>Pay using</small><b>Google Pay</b></p><button>Change ›</button></div><div class="slide-pay" [class.loading]="paying"><input #slider type="range" min="0" max="100" step="1" [(ngModel)]="slideValue" aria-label="Slide to pay" (change)="finishSlide(slider)"><span>»</span><b>{{paying?'Processing…':'Slide to Pay | ₹'+state.total}}</b></div><p *ngIf="paymentError" class="form-error" role="alert">{{paymentError}}</p></section>
  </main>` })
export class CheckoutPageComponent {
  @ViewChild('note') note?:ElementRef<HTMLTextAreaElement>; editingNote=false; slideValue=0; paying=false; paymentError='';
  constructor(public readonly state:ChotaBossStateService,private readonly router:Router,private readonly route:ActivatedRoute){}
  editNote():void{this.editingNote=!this.editingNote;setTimeout(()=>this.note?.nativeElement.focus());}
  saveNote(value:string):void{this.state.setNote(value);this.editingNote=false;}
  finishSlide(input:HTMLInputElement):void{if(this.slideValue>=92){void this.pay();}else{this.slideValue=0;input.value='0';}}
  async pay():Promise<void>{if(this.paying)return;this.paymentError='';this.paying=true;try{await this.state.placeOrder();this.slideValue=100;void this.router.navigate(['../order/success'], { relativeTo: this.route });}catch(error){this.paymentError=error instanceof Error?error.message:'Payment failed. Try again.';this.slideValue=0;}finally{this.paying=false;}}
}

@Component({ selector: 'cb-order-success', template: `
  <main class="app-page order-success action-page" aria-live="polite"><section class="order-head"><div class="success-check">✓</div><h1>Order Confirmed!</h1><p>Your order has been placed successfully</p><div class="order-id"><span>Order ID</span><b>#{{order?.id || 'ORD-847291'}}</b></div><div class="eta"><b>◷ {{order?.etaMinutes || 34}} min</b><span>ESTIMATED DELIVERY TIME</span></div></section><hr><section class="page-pad"><article class="order-card"><div>⌂ <span><small>DELIVERING TO</small><b>{{order?.address || 'CB904 Salarpuri Gr...'}}</b></span><i>›</i></div><p *ngFor="let line of state.cart"><span>{{line.product.name}}</span><b>₹{{line.product.price*line.quantity}}</b></p><button>View Full Order</button></article><div class="order-totals"><p><span>Item Subtotal</span><b>₹{{order?.subtotal || state.subtotal}}</b></p><p><span>Delivery Fee</span><b>₹{{order?.deliveryFee || state.deliveryFee}}</b></p><p><span>Coupon Discount</span><b class="green">−₹{{order?.discount || state.discount}}</b></p><p><strong>Total Amount</strong><strong>₹{{order?.total || state.total}}</strong></p></div><div class="paid">🌈 &nbsp; Paid via Google Pay</div></section><div class="sticky-action order-actions"><button class="primary">Track Order &nbsp; →</button><a routerLink="../shop">Continue Shopping</a></div></main>` })
export class OrderSuccessPageComponent { get order(){return this.state.order;} constructor(public readonly state:ChotaBossStateService){} }
