export const dynamicFormConstants = {
  INDIAN_STATES_LIST: [
    { id: '1', displayName: 'Andhra Pradesh', value: 'AP' },
    { id: '2', displayName: 'Arunachal Pradesh', value: 'AR' },
    { id: '3', displayName: 'Assam', value: 'AS' },
    { id: '4', displayName: 'Bihar', value: 'BR' },
    { id: '5', displayName: 'Chattisgarh', value: 'CG' },
    { id: '6', displayName: 'Goa', value: 'GA' },
    { id: '7', displayName: 'Gujarat', value: 'GJ' },
    { id: '8', displayName: 'Haryana', value: 'HR' },
    { id: '9', displayName: 'Himachal Pradesh', value: 'HP' },
    { id: '10', displayName: 'Jammu & Kashmir', value: 'JK' },
    { id: '11', displayName: 'Jharkhand', value: 'JH' },
    { id: '12', displayName: 'Karnataka', value: 'KA' },
    { id: '13', displayName: 'Kerala', value: 'KL' },
    { id: '14', displayName: 'Madhya Pradesh', value: 'MP' },
    { id: '15', displayName: 'Maharashtra', value: 'MH' },
    { id: '16', displayName: 'Manipur', value: 'MN' },
    { id: '17', displayName: 'Meghalaya', value: 'ML' },
    { id: '18', displayName: 'Mizoram', value: 'MZ' },
    { id: '19', displayName: 'Nagaland', value: 'NL' },
    { id: '20', displayName: 'Odisha', value: 'OR' },
    { id: '21', displayName: 'Punjab', value: 'PB' },
    { id: '22', displayName: 'Rajasthan', value: 'RJ' },
    { id: '23', displayName: 'Sikkim', value: 'SK' },
    { id: '24', displayName: 'Tamil Nadu', value: 'TN' },
    { id: '25', displayName: 'Telangana', value: 'TS' },
    { id: '26', displayName: 'Tripura', value: 'TR' },
    { id: '27', displayName: 'Uttarakhand', value: 'UK' },
    { id: '28', displayName: 'Uttar Pradesh', value: 'UP' },
    { id: '29', displayName: 'West Bengal', value: 'WB' },
    { id: '30', displayName: 'Andaman & Nicobar', value: 'AN' },
    { id: '31', displayName: 'Chandigarh', value: 'CH' },
    { id: '32', displayName: 'Dadra and Nagar Haveli', value: 'DN' },
    { id: '33', displayName: 'Daman & Diu', value: 'DD' },
    { id: '34', displayName: 'Delhi', value: 'DL' },
    { id: '35', displayName: 'Lakshadweep', value: 'LD' },
    { id: '36', displayName: 'Puducherry', value: 'PY' },
    { id: '37', displayName: 'Ladakh', value: 'LK' },
  ],
  COUNTRIES_LIST: [
    { id: '1', displayName: 'Afghanistan', value: 'AF' },
    { id: '2', displayName: 'Albania', value: 'AL' },
    { id: '3', displayName: 'Algeria', value: 'DZ' },
    { id: '4', displayName: 'Andorra', value: 'AD' },
    { id: '5', displayName: 'Angola', value: 'AO' },
    { id: '6', displayName: 'Antigua and Barbuda', value: 'AG' },
    { id: '7', displayName: 'Argentina', value: 'AR' },
    { id: '8', displayName: 'Armenia', value: 'AM' },
    { id: '9', displayName: 'Australia', value: 'AU' },
    { id: '10', displayName: 'Austria', value: 'AT' },
    { id: '11', displayName: 'Azerbaijan', value: 'AZ' },
    { id: '12', displayName: 'Bahamas', value: 'BS' },
    { id: '13', displayName: 'Bahrain', value: 'BH' },
    { id: '14', displayName: 'Bangladesh', value: 'BD' },
    { id: '15', displayName: 'Barbados', value: 'BB' },
    { id: '16', displayName: 'Belarus', value: 'BY' },
    { id: '17', displayName: 'Belgium', value: 'BE' },
    { id: '18', displayName: 'Belize', value: 'BZ' },
    { id: '19', displayName: 'Benin', value: 'BJ' },
    { id: '20', displayName: 'Bhutan', value: 'BT' },
    { id: '21', displayName: 'Bolivia', value: 'BO' },
    { id: '22', displayName: 'Bosnia and Herzegovina', value: 'BA' },
    { id: '23', displayName: 'Botswana', value: 'BW' },
    { id: '24', displayName: 'Brazil', value: 'BR' },
    { id: '25', displayName: 'Brunei', value: 'BN' },
    { id: '26', displayName: 'Bulgaria', value: 'BG' },
    { id: '27', displayName: 'Burkina Faso', value: 'BF' },
    { id: '28', displayName: 'Burundi', value: 'BI' },
    { id: '29', displayName: 'Cabo Verde', value: 'CV' },
    { id: '30', displayName: 'Cambodia', value: 'KH' },
    { id: '31', displayName: 'Cameroon', value: 'CM' },
    { id: '32', displayName: 'Canada', value: 'CA' },
    { id: '33', displayName: 'Central African Republic', value: 'CF' },
    { id: '34', displayName: 'Chad', value: 'TD' },
    { id: '35', displayName: 'Chile', value: 'CL' },
    { id: '36', displayName: 'China', value: 'CN' },
    { id: '37', displayName: 'Colombia', value: 'CO' },
    { id: '38', displayName: 'Comoros', value: 'KM' },
    { id: '39', displayName: 'Congo (Congo-Brazzaville)', value: 'CG' },
    { id: '40', displayName: 'Costa Rica', value: 'CR' },
    { id: '41', displayName: 'Croatia', value: 'HR' },
    { id: '42', displayName: 'Cuba', value: 'CU' },
    { id: '43', displayName: 'Cyprus', value: 'CY' },
    { id: '44', displayName: 'Czech Republic', value: 'CZ' },
    { id: '45', displayName: 'Democratic Republic of the Congo', value: 'CD' },
    { id: '46', displayName: 'Denmark', value: 'DK' },
    { id: '47', displayName: 'Djibouti', value: 'DJ' },
    { id: '48', displayName: 'Dominica', value: 'DM' },
    { id: '49', displayName: 'Dominican Republic', value: 'DO' },
    { id: '50', displayName: 'Ecuador', value: 'EC' },
    { id: '51', displayName: 'Egypt', value: 'EG' },
    { id: '52', displayName: 'El Salvador', value: 'SV' },
    { id: '53', displayName: 'Equatorial Guinea', value: 'GQ' },
    { id: '54', displayName: 'Eritrea', value: 'ER' },
    { id: '55', displayName: 'Estonia', value: 'EE' },
    { id: '56', displayName: 'Eswatini', value: 'SZ' },
    { id: '57', displayName: 'Ethiopia', value: 'ET' },
    { id: '58', displayName: 'Fiji', value: 'FJ' },
    { id: '59', displayName: 'Finland', value: 'FI' },
    { id: '60', displayName: 'France', value: 'FR' },
    { id: '61', displayName: 'Gabon', value: 'GA' },
    { id: '62', displayName: 'Gambia', value: 'GM' },
    { id: '63', displayName: 'Georgia', value: 'GE' },
    { id: '64', displayName: 'Germany', value: 'DE' },
    { id: '65', displayName: 'Ghana', value: 'GH' },
    { id: '66', displayName: 'Greece', value: 'GR' },
    { id: '67', displayName: 'Grenada', value: 'GD' },
    { id: '68', displayName: 'Guatemala', value: 'GT' },
    { id: '69', displayName: 'Guinea', value: 'GN' },
    { id: '70', displayName: 'Guinea-Bissau', value: 'GW' },
    { id: '71', displayName: 'Guyana', value: 'GY' },
    { id: '72', displayName: 'Haiti', value: 'HT' },
    { id: '73', displayName: 'Honduras', value: 'HN' },
    { id: '74', displayName: 'Hungary', value: 'HU' },
    { id: '75', displayName: 'Iceland', value: 'IS' },
    { id: '76', displayName: 'India', value: 'IN' },
    { id: '77', displayName: 'Indonesia', value: 'ID' },
    { id: '78', displayName: 'Iran', value: 'IR' },
    { id: '79', displayName: 'Iraq', value: 'IQ' },
    { id: '80', displayName: 'Ireland', value: 'IE' },
    { id: '81', displayName: 'Israel', value: 'IL' },
    { id: '82', displayName: 'Italy', value: 'IT' },
    { id: '83', displayName: 'Jamaica', value: 'JM' },
    { id: '84', displayName: 'Japan', value: 'JP' },
    { id: '85', displayName: 'Jordan', value: 'JO' },
    { id: '86', displayName: 'Kazakhstan', value: 'KZ' },
    { id: '87', displayName: 'Kenya', value: 'KE' },
    { id: '88', displayName: 'Kiribati', value: 'KI' },
    { id: '89', displayName: 'Kuwait', value: 'KW' },
    { id: '90', displayName: 'Kyrgyzstan', value: 'KG' },
    { id: '91', displayName: 'Laos', value: 'LA' },
    { id: '92', displayName: 'Latvia', value: 'LV' },
    { id: '93', displayName: 'Lebanon', value: 'LB' },
    { id: '94', displayName: 'Lesotho', value: 'LS' },
    { id: '95', displayName: 'Liberia', value: 'LR' },
    { id: '96', displayName: 'Libya', value: 'LY' },
    { id: '97', displayName: 'Liechtenstein', value: 'LI' },
    { id: '98', displayName: 'Lithuania', value: 'LT' },
    { id: '99', displayName: 'Luxembourg', value: 'LU' },
    { id: '100', displayName: 'Madagascar', value: 'MG' },
    { id: '101', displayName: 'Malawi', value: 'MW' },
    { id: '102', displayName: 'Malaysia', value: 'MY' },
    { id: '103', displayName: 'Maldives', value: 'MV' },
    { id: '104', displayName: 'Mali', value: 'ML' },
    { id: '105', displayName: 'Malta', value: 'MT' },
    { id: '106', displayName: 'Marshall Islands', value: 'MH' },
    { id: '107', displayName: 'Mauritania', value: 'MR' },
    { id: '108', displayName: 'Mauritius', value: 'MU' },
    { id: '109', displayName: 'Mexico', value: 'MX' },
    { id: '110', displayName: 'Micronesia', value: 'FM' },
    { id: '111', displayName: 'Moldova', value: 'MD' },
    { id: '112', displayName: 'Monaco', value: 'MC' },
    { id: '113', displayName: 'Mongolia', value: 'MN' },
    { id: '114', displayName: 'Montenegro', value: 'ME' },
    { id: '115', displayName: 'Morocco', value: 'MA' },
    { id: '116', displayName: 'Mozambique', value: 'MZ' },
    { id: '117', displayName: 'Myanmar (Burma)', value: 'MM' },
    { id: '118', displayName: 'Namibia', value: 'NA' },
    { id: '119', displayName: 'Nauru', value: 'NR' },
    { id: '120', displayName: 'Nepal', value: 'NP' },
    { id: '121', displayName: 'Netherlands', value: 'NL' },
    { id: '122', displayName: 'New Zealand', value: 'NZ' },
    { id: '123', displayName: 'Nicaragua', value: 'NI' },
    { id: '124', displayName: 'Niger', value: 'NE' },
    { id: '125', displayName: 'Nigeria', value: 'NG' },
    { id: '126', displayName: 'North Korea', value: 'KP' },
    { id: '127', displayName: 'North Macedonia', value: 'MK' },
    { id: '128', displayName: 'Norway', value: 'NO' },
    { id: '129', displayName: 'Oman', value: 'OM' },
    { id: '130', displayName: 'Pakistan', value: 'PK' },
    { id: '131', displayName: 'Palau', value: 'PW' },
    { id: '132', displayName: 'Panama', value: 'PA' },
    { id: '133', displayName: 'Papua New Guinea', value: 'PG' },
    { id: '134', displayName: 'Paraguay', value: 'PY' },
    { id: '135', displayName: 'Peru', value: 'PE' },
    { id: '136', displayName: 'Philippines', value: 'PH' },
    { id: '137', displayName: 'Poland', value: 'PL' },
    { id: '138', displayName: 'Portugal', value: 'PT' },
    { id: '139', displayName: 'Qatar', value: 'QA' },
    { id: '140', displayName: 'Romania', value: 'RO' },
    { id: '141', displayName: 'Russia', value: 'RU' },
    { id: '142', displayName: 'Rwanda', value: 'RW' },
    { id: '143', displayName: 'Saint Kitts and Nevis', value: 'KN' },
    { id: '144', displayName: 'Saint Lucia', value: 'LC' },
    { id: '145', displayName: 'Saint Vincent and the Grenadines', value: 'VC' },
    { id: '146', displayName: 'Samoa', value: 'WS' },
    { id: '147', displayName: 'San Marino', value: 'SM' },
    { id: '148', displayName: 'Sao Tome and Principe', value: 'ST' },
    { id: '149', displayName: 'Saudi Arabia', value: 'SA' },
    { id: '150', displayName: 'Senegal', value: 'SN' },
    { id: '151', displayName: 'Serbia', value: 'RS' },
    { id: '152', displayName: 'Seychelles', value: 'SC' },
    { id: '153', displayName: 'Sierra Leone', value: 'SL' },
    { id: '154', displayName: 'Singapore', value: 'SG' },
    { id: '155', displayName: 'Slovakia', value: 'SK' },
    { id: '156', displayName: 'Slovenia', value: 'SI' },
    { id: '157', displayName: 'Solomon Islands', value: 'SB' },
    { id: '158', displayName: 'Somalia', value: 'SO' },
    { id: '159', displayName: 'South Africa', value: 'ZA' },
    { id: '160', displayName: 'South Korea', value: 'KR' },
    { id: '161', displayName: 'South Sudan', value: 'SS' },
    { id: '162', displayName: 'Spain', value: 'ES' },
    { id: '163', displayName: 'Sri Lanka', value: 'LK' },
    { id: '164', displayName: 'Sudan', value: 'SD' },
    { id: '165', displayName: 'Suriname', value: 'SR' },
    { id: '166', displayName: 'Sweden', value: 'SE' },
    { id: '167', displayName: 'Switzerland', value: 'CH' },
    { id: '168', displayName: 'Syria', value: 'SY' },
    { id: '169', displayName: 'Taiwan', value: 'TW' },
    { id: '170', displayName: 'Tajikistan', value: 'TJ' },
    { id: '171', displayName: 'Tanzania', value: 'TZ' },
    { id: '172', displayName: 'Thailand', value: 'TH' },
    { id: '173', displayName: 'Timor-Leste', value: 'TL' },
    { id: '174', displayName: 'Togo', value: 'TG' },
    { id: '175', displayName: 'Tonga', value: 'TO' },
    { id: '176', displayName: 'Trinidad and Tobago', value: 'TT' },
    { id: '177', displayName: 'Tunisia', value: 'TN' },
    { id: '178', displayName: 'Turkey', value: 'TR' },
    { id: '179', displayName: 'Turkmenistan', value: 'TM' },
    { id: '180', displayName: 'Tuvalu', value: 'TV' },
    { id: '181', displayName: 'Uganda', value: 'UG' },
    { id: '182', displayName: 'Ukraine', value: 'UA' },
    { id: '183', displayName: 'United Arab Emirates', value: 'AE' },
    { id: '184', displayName: 'United Kingdom', value: 'GB' },
    { id: '185', displayName: 'United States of America', value: 'US' },
    { id: '186', displayName: 'Uruguay', value: 'UY' },
    { id: '187', displayName: 'Uzbekistan', value: 'UZ' },
    { id: '188', displayName: 'Vanuatu', value: 'VU' },
    { id: '189', displayName: 'Vatican City', value: 'VA' },
    { id: '190', displayName: 'Venezuela', value: 'VE' },
    { id: '191', displayName: 'Vietnam', value: 'VN' },
    { id: '192', displayName: 'Yemen', value: 'YE' },
    { id: '193', displayName: 'Zambia', value: 'ZM' },
    { id: '194', displayName: 'Zimbabwe', value: 'ZW' },
  ],
};
