export const projectConstants = {
    "ROOTUIPATH": "http://localhost:4300",
    "TEMPLATE": "https://d38qirwztuxwob.cloudfront.net/template",
    "HOME": "https://d38qirwztuxwob.cloudfront.net/home",
    // "template1": "https://d38qirwztuxwob.cloudfront.net/template1",
    // "TEMPLATE": "http://localhost:4201",
    // "HOME": "http://localhost:4204",
    "template1": "http://localhost:4501",
    // "template1": "https://d38qirwztuxwob.cloudfront.net/template1",
    "template2": "http://localhost:4502",
    "template3": "http://localhost:4503",
    "template4": "http://localhost:4504",
    "template5": "http://localhost:4505",
    "template6": "http://localhost:4506",
    "template7": "http://localhost:4507",
    "template8": "http://localhost:4508",
    "template9": "http://localhost:4509",
    "template10": "http://localhost:4510",
    "template11": "http://localhost:4511",
    "template12": "http://localhost:4512",
    "APIENDPOINT": "https://scale.jaldee.com/v1/rest/",
    "S3ENDPOINT": "https://jaldeeuiscale.s3.ap-south-1.amazonaws.com/",
    "SAPATH": "https://sascale.jaldee.com/superadmin/rest/mgmt/",
    "I8NPATH": "https://d2199iy1o5ikw9.cloudfront.net/",
    "CDNURL": "https://d2199iy1o5ikw9.cloudfront.net/",
    "GOOGLEAPIKEY": "AIzaSyDYIC4RIJNisNqXWDhe8y07EPSy9rHJ3-o",
    "UNIQUEID": null
}