export const imageConstants = {
    "bizyGlobe": 'assets/images/BG_icon.png',
    "youtube": 'assets/images/Youtube.svg',
    "instagram": 'assets/images/instagram.svg',
    "website": 'assets/images/Globe.svg',
    "twitter": 'assets/images/Twitter.svg',
    "linkedin": 'assets/images/LINKEDIN.svg',
    "pinterest": 'assets/images/Pintrest.svg',
    "facebook": 'assets/images/Facebook.svg',
    "whatsapp": 'assets/images/whatsapp.svg',
    "share": 'assets/images/Share.svg',
    "phone_no": 'assets/images/Phone.svg',
    "email_id": 'assets/images/Email.svg',
    "serviceicon-bg": "assets/images/Serviceimg5.jpg",
    "signal-1": 'assets/images/teleservice/signal-1.PNG',
    "signal-2":'assets/images/teleservice/signal-2.PNG',
    "signal-3":'assets/images/teleservice/signal-3.PNG',
    "signal-4":'assets/images/teleservice/signal-4.PNG',
    "signal-5":'assets/images/teleservice/signal-5.PNG',
    "wtsapvid-icon":'assets/images/teleservice/whatsapVideo.svg',
    "jaldeevideo-icon":'assets/images/teleservice/jaldeevideo.svg',
    "phon-icon":'assets/images/teleservice/audio.svg',
    "wtsapaud-icon":'assets/images/teleservice/whatsapp_audio.svg',
    "meet-icon": 'assets/images/teleservice/gmeet.svg',
    "zoom-icon": 'assets/images/teleservice/Zoom-01.svg'
};
